env:
  KNAPSACK_PRO_REPO_PATH: "/Users/artur/Documents/github/knapsack-pro/knapsack_pro-ruby"
  # allow to run the same set of test files on retry for parallel job
  # https://github.com/KnapsackPro/knapsack_pro-ruby#knapsack_pro_fixed_queue_split-remember-queue-split-on-retry-ci-node
  KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true

steps:
  - command: "bundle exec rake knapsack_pro:queue:rspec"
    parallelism: 2
