version: "1.0"

stages:
  - "clone"
  - "build"
  - "tests"

indicators:
  - environment: &my_common_envs |-
      USE_KNAPSACK_PRO_FROM_RUBYGEMS=true
      RAILS_ENV=test
      KNAPSACK_PRO_CI_NODE_TOTAL=2
      KNAPSACK_PRO_CI_NODE_BUILD_ID=${{CF_BUILD_ID}}
      KNAPSACK_PRO_BRANCH=${{CF_BRANCH}}
      KNAPSACK_PRO_COMMIT_HASH=${{CF_REVISION}}
      PGHOST=postgres
      PGUSER=rails-app-with-knapsack_pro
      PGPASSWORD=password

steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  BuildTestDockerImage:
    title: Building Test Docker image
    type: build
    arguments:
      image_name: '${{CF_ACCOUNT}}/${{CF_REPO_NAME}}-test'
      tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
      dockerfile: Test.Dockerfile
    stage: "build"

  run_parallel_tests:
    title: "Run tests with Knapsack Pro"
    type: parallel
    stage: "tests"
    steps:
      node_0:
        image: '${{BuildTestDockerImage}}'
        environment:
          - *my_common_envs
          - KNAPSACK_PRO_CI_NODE_INDEX=0
        working_directory: /src
        commands:
          - bin/rails db:prepare
          - bundle exec rake knapsack_pro:queue:rspec
        fail_fast: false
        services:
          composition:
            postgres:
              image: postgres:latest
              environment:
                - POSTGRES_DB=rails-app-with-knapsack_pro_test
                - POSTGRES_PASSWORD=password
                - POSTGRES_USER=rails-app-with-knapsack_pro
              ports:
                - 5432

      node_1:
        image: '${{BuildTestDockerImage}}'
        environment:
          - *my_common_envs
          - KNAPSACK_PRO_CI_NODE_INDEX=1
        working_directory: /src
        commands:
          - bin/rails db:prepare
          - bundle exec rake knapsack_pro:queue:rspec
        fail_fast: false
        services:
          composition:
            postgres:
              image: postgres:latest
              environment:
                - POSTGRES_DB=rails-app-with-knapsack_pro_test
                - POSTGRES_PASSWORD=password
                - POSTGRES_USER=rails-app-with-knapsack_pro
              ports:
                - 5432
